(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Fqa=function(a){a.u||(a.u=new g.Xn,g.H(a,a.u));return a.u},J2=function(a){a.R("cardstatechange",g.BL(a)&&g.CL(a)?1:0)},Gqa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Zj&&a.dataset){if(g.lc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.jd("pollChoiceIndex"))},Hqa=function(a){return Math.pow(a,3)},Iqa=function(a){return 3*a*a-2*a*a*a},K2=function(a,b){(0,g.y)(b,function(c){c={csn:a,
ve:g.Ir(c),eventType:4};var d={jk:g.Tr(a),si:a};"UNDEFINED_CSN"==a?g.fs("visualElementShown",c,d):g.Zq("visualElementShown",c,g.gr,d)})},L2=function(a,b){(0,g.y)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.Ir(c),eventType:d?16:8};d={jk:g.Tr(a),si:a,vE:d};"UNDEFINED_CSN"==a?g.fs("visualElementHidden",c,d):g.Zq("visualElementHidden",c,g.gr,d)})},O2=function(a){a=g.Qa(a);
delete M2[a];g.ac(M2)&&N2&&N2.stop()},Kqa=function(){N2||(N2=new g.J(function(){Jqa()},20));
var a=N2;a.isActive()||a.start()},Jqa=function(){var a=(0,g.I)();
g.Ob(M2,function(b){Lqa(b,a)});
g.ac(M2)||Kqa()},P2=function(a,b,c,d){g.Mn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.J=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.F=null},Lqa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.F);a.F=b;Mqa(a,a.progress);1==a.progress?(a.o=0,O2(a),a.wd(),a.A()):1==a.o&&a.nt()},Mqa=function(a,b){g.Na(a.G)&&(b=a.G(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.J[c]-a.w[c])*b+a.w[c]},Nqa=function(a,b){g.oe.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},Q2=function(a,b,c,d,e){P2.call(this,b,c,d,e);
this.element=a},R2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
Q2.call(this,a,b,c,d,e)},S2=function(a){g.B.call(this);
this.u=a||window;this.o=[]},Oqa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.Oq(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},T2=function(a){return a.baseUrl||null},Pqa=function(a,b,c){function d(tb){var Ya=tb.hovercardButton;
if(!Ya)return null;Ya=Ya.subscribeButtonRenderer;if(!Ya)return null;var uc=f(Ya.unsubscribedButtonText),ff=f(Ya.subscribedButtonText);if(Ya.subscribed){var gf=f(Ya.subscriberCountWithUnsubscribeText);var Ch=f(Ya.subscriberCountText)}else gf=f(Ya.subscriberCountText),Ch=f(Ya.subscriberCountWithSubscribeText);var hf=null;return tb.signinEndpoint&&(hf=g.Wb(tb,"signinEndpoint","webNavigationEndpointData","url"),!hf)?null:uc&&(ff||hf)?{subscribed:Ya.subscribed,subscribeText:uc,subscribeCount:gf,unsubscribeText:ff,
unsubscribeCount:Ch,enabled:Ya.enabled,signinUrl:hf,classic:tb.useClassicSubscribeButton}:null}
function e(tb){if(tb){var Ya=[],uc=tb.videoId;uc&&Ya.push("v="+uc);(uc=tb.playlistId)&&Ya.push("list="+uc);(tb=tb.startTimeSeconds)&&Ya.push("t="+tb);return"/watch?"+Ya.join("&")}}
function f(tb){if(!tb)return null;var Ya=tb.simpleText;return Ya?Ya:tb.runs?(0,g.A)(tb.runs,function(uc){return uc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=null,t=null,u=null,z=null,C=!1,D=null,E=null,G=null,F=null,ka=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,p=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(C=g.Wb(l,"browseEndpoint","browseId"))z=C,m="/channel/"+z;n=!1;p="new";(C=!!b.isSubscribe)?D=d(b):E=f(b.subscribersText)}else"WEBSITE"==
k?((G=g.Wb(l,"urlEndpoint","url"))&&(m=G),n=!0,p="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(ka=f(b.additionalFeesText)),(n=g.Wb(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=g.Wb(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:null,Cb="";if(b.metadata){var Hc=f(b.metadata);Hc&&(Cb=Hc)}return{id:"element-"+c,type:k,title:f(b.title),metadata:Cb,callToAction:f(b.callToAction),
Aw:b.image,iconUrl:G,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:D,subscribersText:E,isSubscribe:C,targetUrl:m,WF:n,Nb:{itct:X},QO:p,Zj:a?a:null,aG:b.isPlaceholder,impressionUrls:(0,g.A)(b.impressionUrls||[],T2),MF:(0,g.A)(b.hovercardShowUrls||[],T2),clickUrls:(0,g.A)(l.loggingUrls||[],T2),visualElement:g.Hr(b.trackingParams),
productPrice:F,additionalFeesText:ka}},U2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.A)(a.impressionUrls||[],T2);a.trackingParams&&(c.visualElement=g.Hr(a.trackingParams));var d=(0,g.A)(a.elements||[],function(e,f){return Pqa(b,e,f)});
c.elements=(0,g.ae)(d,function(e){return!!e});
return c},V2=function(a){g.NP.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.H=[];a=a.N();this.J=g.Ax(a)||g.Cx(a);this.P=!0;this.G=0;this.B=new g.P(this);g.H(this,this.B);this.B.L(this.player,g.VD("creatorendscreen"),this.FG);this.B.L(this.player,"crx_creatorendscreen",this.GG);this.B.L(this.player,"resize",this.My);this.B.L(window,"focus",this.MN);this.load();var b=g.Vd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.le(this,function(){g.$d(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Qqa=function(a){return a.player.getVideoData().uc?"current":a.J?"new":"current"},W2=function(a){return"creator-endscreen-editor"===a.player.N().playerStyle},X2=function(a,b,c){c=void 0===c?!0:c;
g.dR(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&Rqa(a);c=[];d=new g.SD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.N().o||(a.w=new g.V({D:"div",I:"ytp-ce-shadow"}),g.ML(a.player,a.w.element,4),a.C=new g.fM(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Sqa(a,e);a.o[e.id]=f;a.F[e.id]=e;g.ML(a.player,f.element,4);var k=new g.SD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Tqa(a,f,e)}g.IL(a.player,c);
a.My()}},Rqa=function(a){var b=g.Qr(),c=g.Sr();
c&&b&&a.u.visualElement&&g.gs(c,b,[a.u.visualElement])},Sqa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",X:["ytp-ce-element","ytp-ce-video"],M:{tabindex:"0","aria-label":b.Zj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",M:Y2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",M:{href:Z2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],M:{dir:g.gn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.V(c);break;case "PLAYLIST":c={D:"div",X:["ytp-ce-element","ytp-ce-playlist"],M:{tabindex:"0","aria-label":b.Zj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",M:Y2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",M:{href:Z2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],M:{dir:g.gn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-playlist-count",K:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.V(c);break;case "CHANNEL":c={D:"div",X:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],M:{tabindex:"0","aria-label":b.Zj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",X:["ytp-ce-channel-title","ytp-ce-link"],M:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.gn(b.title||"")},W:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",K:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",X:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:Y2(b)}]};c=new g.V(c);var d=g.Hd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.N().o){var e=null;var f=b.Nb.itct}else e="endscreen",f=null;e=new g.tQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={D:"div",X:["ytp-ce-element","ytp-ce-website"],M:{tabindex:"0","aria-label":b.Zj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",I:"ytp-ce-expanding-overlay-body",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-website-title",M:{dir:g.gn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-website-metadata",W:b.metadata},{D:"a",X:["ytp-ce-website-goto","ytp-ce-link"],M:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:Y2(b)},{D:"div",I:"ytp-ce-expanding-icon",M:Uqa(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
K:[{D:"div",I:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",X:["ytp-ce-element","ytp-ce-merchandise"],M:{tabindex:"0","aria-label":b.Zj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",
I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-merchandise-title",M:{dir:g.gn(b.title||"")},W:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",X:["ytp-ce-merchandise-goto","ytp-ce-link"],M:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:Y2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.V(c)}b.aG&&g.K(c.element,"ytp-ce-placeholder");return c},Y2=function(a){if(a.Aw)var b=a.Aw.thumbnails;
return Uqa(b?b[b.length-1].url:null)},Uqa=function(a){return a?{style:"background-image: url("+a+")"}:{}},Tqa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ia("mouseenter",(0,g.x)(a.qs,a,b,c));b.ia("mouseleave",(0,g.x)(a.xt,a,b,c));a.player.N().o||b.ia("click",(0,g.x)(function(l){g.K(l.element,"ytp-ce-element-hover")},a,b));
b.ia("click",(0,g.x)(a.rA,a,c));b.ia("keypress",(0,g.x)(a.rA,a,c));b.ia("focus",(0,g.x)(function(l,m){this.qs(l,m)},a,b,c));
b.ia("blur",(0,g.x)(function(l,m){this.xt(l,m)},a,b,c));
b.ia("touchstart",(0,g.x)(a.qs,a,b,c));var f=g.Jd("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Kn(b.element,"ytp-ce-element-hover");g.Kn(b.element,"ytp-ce-force-expand")});
b.ia("keydown",(0,g.x)(function(l,m){this.P=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.K(l.element,"ytp-ce-force-expand"),$2(this,m.id,!0)):(g.Kn(l.element,"ytp-ce-force-expand"),g.Kn(l.element,"ytp-ce-element-hover"),$2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ia("blur",g.Ra(function(){"none"!=m.style.display&&a.P&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.Jd("ytp-sb-subscribe",b.element));c(g.Jd("ytp-sb-unsubscribe",b.element));b.ia("focus",d);b.ia("blur",e)},Z2=function(a,b){var c=a.player.N();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.by(c)+b}else return"";return b},$2=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.L(a.o[d].element,"ytp-ce-element-shadow-show",c)},a3=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||W2(a))c&&c();else{b=Vqa(a,b);var e=0,f=!1,k=new g.J(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Qp(b[a],d)}},b3=function(a,b,c){a3(a,b.clickUrls,c);
(a=g.Sr())&&b.WF&&g.is(a,b.visualElement)},Vqa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Wqa(b[e],c));return d},Wqa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Xqa=function(a){return g.La(a)&&a.length?a[0]:a},c3=function(a){return"string"===typeof a?a:""},d3=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Zqa=function(a){var b=Yqa;
if(null==a)return null;if(g.Ma(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},$qa=function(a){this.externalId=a},ara=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},e3=function(a){if(!a)return null;
var b=g.Ec(c3(a.value));b=g.Cc(b);if(!b)return null;var c=d3(a.target,bra,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new ara(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},f3=function(a){return a.value?a.value:null},cra=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Yqa=function(a){if(!a)return null;
var b=d3(a.type,dra),c=d3(a.trigger,era),d=Xqa(a.url);d=e3(d?d:null);a=Xqa(a.subscribeData);var e=a?a:null;e?(a=c3(e.external_user_id),e=c3(e.subscription_token),a=a&&e?new $qa(a):null):a=null;return b?new cra(b,c,d,a):null},fra=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},hra=function(a){return(a=gra(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},gra=function(a,b){return g.Za(a.o,b,void 0)},ira=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},jra=function(a,b){this.merchant=a;
this.price=b},kra=function(a){this.o=a},lra=function(a,b,c){b&&(c?g3(a,(0,g.A)(b,g.Ra(function(d,e){return g.en(e,d)},c))):g3(a,b))},g3=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Qp(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},mra=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.fb=c;this.videoData=d;this.logger=e;this.aa=f;this.u=k},h3=function(a,b){this.o=a;
this.w=b},pra=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(nra(b,k))},a);
var d={D:"ul",M:{role:"radiogroup"},K:c},e={};b.xi&&(e["aria-label"]=g.LM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",I:"iv-card-content",K:[i3("h2",e,b.title),{D:"form",K:[{D:"fieldset",K:[d]}]}]}];b.xi&&(f.push("iv-card-unavailable"),d.push({D:"div",X:["iv-card-sign-in"],K:[{D:"h2",W:"Want to vote?"},{D:"a",X:["iv-card-sign-in-button","iv-button"],M:{href:f3(b.xi)},K:[{D:"span",X:["iv-button-content"],W:"Sign in"}]}]}));f=new g.V({D:"div",
X:f,K:d});d=f.element;ora(b,d);Oqa(a.o.o,d,g.Ra(a.A,b),a);(0,g.y)(g.Id("iv-card-poll-choice-input",d),function(k){this.o.o.ia(k,"focus",g.Ra(this.u,!0));this.o.o.ia(k,"blur",g.Ra(this.u,!1))},a);
b.xi&&(d=g.Jd("iv-card-sign-in-button",d),a.w(d,b.xi,b.id,b.Nb,b.Gc.click,5));return f},qra=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.mP?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.ZF&&b.Vv?{D:"span",X:d,M:e,W:b.Vv}:"";c={D:"div",X:["iv-card",c],K:[{D:"a",I:"iv-click-target",M:{href:f3(b.url)},K:[j3(b.Ci,d?{D:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{D:"div",I:"iv-card-content",K:[{D:"h2",I:"iv-card-primary-link",W:b.title},k3(a,b)]}]}]};c=new g.V(c);l3(a,g.Id("iv-click-target",c.element),b,b.url);return c},m3=function(a){return a.customMessage?
i3("div","iv-card-message",a.customMessage):""},j3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",M:{style:c},K:d}},k3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(i3("li","",d))},a);
return{D:"ul",I:"iv-card-meta-info",K:c}},nra=function(a,b){return{D:"li",
I:ira(a,b.index),K:[{D:"label",K:[{D:"input",I:"iv-card-poll-choice-input",M:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",I:"iv-card-poll-choice-text",K:[{D:"span",I:"iv-card-poll-choice-percent"},i3("span",void 0,b.desc)]}]},{D:"div",I:"iv-card-poll-result",K:[{D:"div",I:"iv-card-poll-result-bar"}]}]}},i3=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.La(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.gn(c);return{D:a,M:b,W:c}},rra=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Mm&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Mm+");");c.dir=g.gn(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",X:b,M:c,K:d}},ora=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Jd(ira(a,e.index),b);e=e.count/c;null==a.De&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.De==d);f.getElementsByTagName("input")[0].checked=a.De==d;var k=Math.floor(100*e).toFixed(0),l=g.Jd("iv-card-poll-choice-percent",f);g.de(l,g.LM("$PERCENT%",{PERCENT:k}));f=g.Jd("iv-card-poll-result-bar",f);g.th(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.De);g.L(b,"iv-card-poll-expanded",
null!=a.De&&1<a.choices.length)},l3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.w(e,d,c.id,c.Nb,c.Gc.click,5)},a)},sra=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},tra=function(a,b){return b?b:sra(a)?"current":"new"},n3=function(a,b){g.B.call(this);
this.o=a;this.context=b;this.Gu=!1},ura=function(a,b,c,d,e){var f=f3(b);
if(f){var k=tra(f,b.target),l=(0,g.x)(function(){b.o&&this.context.aa.pauseVideo();var m=this.context.videoData.uc||!1,n=g.ep(f||"");m&&n&&(n.v||n.list)?g.NT(this.context.aa.app,n.v,c,n.list,!1,void 0):g.PM(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);g3(a.context.logger,d,l,e);sra(f)||(a=g.Sr(),d=c.itct,a&&d&&g.is(a,g.Hr(d)))}},vra=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},o3=function(a,b,c){return{Rx:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
eC:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
tp:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},r3=function(a,b,c){n3.call(this,b,c);
var d=this;this.w=a;this.da=this.Aa=this.C=this.za=!1;this.ea=null;this.Z=new g.J(g.Ia,c.fb.Qa?4E3:3E3);g.H(this,this.Z);this.sa=new g.J(g.Ia);g.H(this,this.sa);this.H=new h3(c,(0,g.x)(this.Jj,this),(0,g.x)(this.Tn,this));this.U=new g.V({D:"div",I:"iv-drawer",M:{id:"iv-drawer"},K:[{D:"div",I:"iv-drawer-header",M:{"aria-role":"heading"},K:[{D:"span",I:"iv-drawer-header-text"},{D:"button",X:["iv-drawer-close-button","ytp-button"],M:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});
g.H(this,this.U);this.F=this.U.element;this.ra=new g.fM(this.U,330);g.H(this,this.ra);this.ya=g.Jd("iv-drawer-header-text",this.F);this.B=g.Jd("iv-drawer-content",this.F);this.A=[];this.xa=this.S=this.G=this.ga=this.u=null;this.V=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Aa&&p3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Aa=d.C)&&q3(d)});
this.O=this.J=this.ca=null;this.P=0},wra=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){p3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){q3(a)});
var c=b.data.headerText;g.de(a.ya,c);a.S&&a.S.setAttribute("title",c);a.ca=g.Hr(b.data.trackingParams);a.O=g.Hr(b.data.closeTrackingParams);a.J=g.Hr(b.data.iconTrackingParams)},xra=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.P;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"simple",teaserText:g.gA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Gc:o3(d,e,d.command),Yd:d.trackingParams?g.Hr(d.trackingParams):null,Td:e.trackingParams?
g.Hr(e.trackingParams):null,pd:f&&f.trackingParams?g.Hr(f.trackingParams):null,imageUrl:t3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.gA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Mm:null,title:d.title?g.gA(d.title):"",customMessage:d.callToAction?g.gA(d.callToAction):"",url:d.command.urlEndpoint.url?e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.command.urlEndpoint.url}):null};u3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"collaborator",teaserText:g.gA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Gc:o3(d,e,d.endpoint),Yd:d.trackingParams?g.Hr(d.trackingParams):null,Td:e.trackingParams?g.Hr(e.trackingParams):null,pd:f&&f.trackingParams?
g.Hr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.gA(d.customText):null,gB:t3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.gA(d.channelName):"",metaInfo:[d.subscriberCountText?g.gA(d.subscriberCountText):""],url:e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};u3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"playlist",teaserText:g.gA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Gc:o3(d,e,d.action),Yd:d.trackingParams?g.Hr(d.trackingParams):null,Td:e.trackingParams?g.Hr(e.trackingParams):null,pd:f&&f.trackingParams?g.Hr(f.trackingParams):
null,Ci:t3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.gA(d.customMessage):null,playlistVideoCount:g.gA(d.playlistVideoCount),title:d.playlistTitle?g.gA(d.playlistTitle):"",metaInfo:[d.channelName?g.gA(d.channelName):"",d.videoCountText?g.gA(d.videoCountText):""],url:e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:vra(d.action)})};u3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"video",teaserText:g.gA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Gc:o3(d,e,d.action),Yd:d.trackingParams?g.Hr(d.trackingParams):null,Td:e.trackingParams?g.Hr(e.trackingParams):null,pd:f&&f.trackingParams?g.Hr(f.trackingParams):null,Ci:t3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.gA(d.lengthString):null,customMessage:d.customMessage?g.gA(d.customMessage):null,title:d.videoTitle?g.gA(d.videoTitle):"",metaInfo:[d.channelName?g.gA(d.channelName):"",d.viewCountText?g.gA(d.viewCountText):""],isLiveNow:!!d.badge,url:e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:vra(d.action)})};u3(a,c)}a.P++},t3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},s3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},zra=function(a,b){var c=yra(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.$d(c.oq),g.fb(a.A,c),a.Om(),v3(a))},p3=function(a,b,c){if(!a.C){a.ra.show();
a.ga=new g.J(function(){g.K(g.sL(a.context.aa),"ytp-iv-drawer-open")},0);
a.ga.start();a.ea=g.Fq(a.B,"mousewheel",(0,g.x)(a.ZG,a));a.C=!0;var d=g.Sr();d&&a.ca&&a.O&&K2(d,[a.ca,a.O]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.wy||(f.wy=!0,lra(a.context.logger,f.card.Gc.Rx,e));d&&K2(d,[f.card.Yd])});
J2(a.w);c&&(a.G=new g.J(function(){a.na=a.S;a.xa.focus()},330),a.G.start())}},q3=function(a){a.C&&(a.ra.hide(),g.Gq(a.ea),a.ea=null,g.Kn(g.sL(a.context.aa),"ytp-iv-drawer-open"),a.C=!1,J2(a.w),a.G&&a.G.stop(),a.G=new g.J(function(){a.na&&(a.na.focus(),a.na=null)},330),a.G.start())},Ara=function(a){var b=g.Jd("iv-drawer-close-button",a.F);
a.context.o.ia(b,"click",a.eE,a);a.context.o.ia(a.B,"touchend",function(){a.Z.start()});
a.context.o.ia(a.B,"scroll",a.rE,a);a.context.u.subscribe("onHideControls",function(){a.da=!0});
a.context.u.subscribe("onShowControls",function(){a.da=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.da=g.In(g.sL(a.w),"ytp-autohide")});
a.V.push(g.Oo("iv-button-shown",a.hG,a));a.V.push(g.Oo("iv-button-hidden",a.gG,a));a.V.push(g.Oo("iv-teaser-shown",a.kG,a));a.V.push(g.Oo("iv-teaser-hidden",a.jG,a));a.V.push(g.Oo("iv-teaser-clicked",a.iG,a))},u3=function(a,b){a.za||(g.Jn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.ML(a.w,a.F,5),Ara(a),a.S=g.Jd("ytp-cards-button",g.sL(a.w)),a.xa=g.Jd("iv-drawer-close-button",a.F),a.za=!0);zra(a,b.id);var c=Bra(a,b);if(c){var d={card:b,oq:c.element,wy:!1},e=Cra(a,d);g.nb(a.A,e,0,d);c.ba(a.B,e);a.Om();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Ra(a.CO,d)):(c=1E3*a.context.aa.getCurrentTime(),5E3>c&&c>b.startMs&&a.KB(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Ra(a.KB,d)),v3(a))}},Bra=function(a,b){switch(b.type){case "simple":var c=a.H;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=rra(b);d={D:"div",X:["iv-card"],K:[{D:"a",I:"iv-click-target",M:{href:f3(b.url)},K:[j3(b.imageUrl,d),{D:"div",I:"iv-card-content",K:[i3("h2",void 0,b.title),e]}]}]};d=new g.V(d);l3(c,g.Id("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={D:"div",X:["iv-card","iv-card-channel"],K:[{D:"a",X:["iv-click-target"],M:{href:f3(b.url),"data-ytid":b.channelId},K:[j3(b.gB),{D:"div",I:"iv-card-content",
K:[m3(b),{D:"h2",I:"iv-card-primary-link",W:b.title},k3(c,b)]}]}]},d=new g.V(d),l3(c,g.Id("iv-click-target",d.element),b,b.url),d;case "episode":return qra(a.H,b,"iv-card-episode");case "movie":return qra(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={D:"div",X:["iv-card","iv-card-playlist"],K:[{D:"a",I:"iv-click-target",M:{href:f3(b.url)},K:[j3(b.Ci,{D:"div",I:"iv-card-image-overlay",K:[{D:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",K:[m3(b),
i3("h2","iv-card-primary-link",b.title),k3(c,b)]}]}]},d=new g.V(d),l3(c,g.Id("iv-click-target",d.element),b,b.url),d;case "poll":return pra(a.H,b);case "productListing":c=a.H;var f=!g.cb(b.offers);d=["iv-card"];e="";var k=rra(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({D:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={D:"div",K:k});d={D:"div",X:d,M:{tabindex:"0"},K:[{D:"a",
X:["iv-card-image","iv-click-target"],M:{style:"background-image: url("+b.imageUrl+");",href:f3(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",K:[b.sponsored?{D:"div",I:"iv-card-sponsored",K:["Sponsored",{D:"div",I:"iv-ad-info-container",K:[{D:"div",I:"iv-ad-info",W:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",K:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",M:{href:f3(b.url)},K:[i3("h2",e,b.title),k]}]}]};d=new g.V(d);
e=g.Vd("span");g.de(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.ub(e,"adInfo");l3(c,g.Id("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{D:"span",X:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",X:["iv-card","iv-card-video"],K:[{D:"a",I:"iv-click-target",M:{href:f3(b.url)},K:[j3(b.Ci,b.videoDuration?{D:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",I:"iv-card-content",
K:[m3(b),i3("h2","iv-card-primary-link",b.title),k3(c,b),d]}]}]},d=new g.V(d),l3(c,g.Id("iv-click-target",d.element),b,b.url),d}return null},Cra=function(a,b){if(0==a.A.length)return 0;
var c=g.$a(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Dra=function(a){return a.u?"productListing"==a.u.card.type:(0,g.si)(a.A,function(b){return"productListing"==b.card.type})},v3=function(a){g.L(g.sL(a.w),"ytp-cards-shopping-active",Dra(a))},Era=function(a,b){if(a.U.Fa()){var c=new P2([0,
a.B.scrollTop],[0,b.oq.offsetTop],600,Iqa);a.context.w.ia(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ia(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.FC(a.U,!0),a.B.scrollTop=b.oq.offsetTop,g.FC(a.U,!1)},w3=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},yra=function(a,b){return g.Za(a.A,function(c){return c.card.id==b})},x3=function(a,b,c){n3.call(this,a,b);
this.annotation=c;this.isActive=!1},Fra=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},y3=function(a,b,c){x3.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.F=this.C=null},z3=function(a,b,c){x3.call(this,a,b,c);
this.J=this.C=this.P=!1;this.G=5E3;this.B=null;this.H=g.Ud("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.F=new g.J(function(){this.u.setAttribute("aria-hidden",!0);g.Oh(this.A,!1);g.Oh(this.w,!0)},700,this);
g.H(this,this.F)},Gra=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=hra(a.annotation),f=b.image_url;if(f){var k=g.Ud("DIV",["iv-promo-img","iv-click-target"]);f=g.Ud("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Ud("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Ud("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Jj(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Ud("A","iv-promo-txt"),g.Zc(f,f3(e)),a.u=f):a.u=g.Ud("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Ud("P",null,g.Ud("STRONG",null,b.text_line_1));var m=g.Ud("P",null,g.Ud("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.R(a.context.fb.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Ud("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Ud("BUTTON",["iv-button","iv-promo-button"],g.Ud("SPAN","iv-button-content",f));var p=g.Ud("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Jj(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.u,"iv-click-target");e&&a.Jj(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Ud("P",null,g.Ud("SPAN",null,b.text_line_1)),
m=g.Ud("P",null,g.Ud("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Ud("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.K(a.u,"iv-click-target"),e&&a.Jj(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);p&&a.H.appendChild(p);c=g.Ud("DIV","iv-promo-actions");a.w=g.Ud("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ia(a.w,"click",g.Ra(a.mr,5E3),a);c.appendChild(a.w);g.Oh(a.w,!1);
a.context.o.ia(a.o,"mouseover",a.pF,a);a.context.o.ia(a.o,"mouseout",a.oF,a);a.context.o.ia(a.o,"touchend",g.Ra(a.mr,5E3),a);a.A=g.Ud("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ia(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.hF:a.gF,a);c.appendChild(a.A);g.Jn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},Hra=function(a){a.C||a.J||a.B||(g.K(a.o,"iv-promo-collapsed"),a.C=!0,a.F.start())},Ira=function(a){a.F.stop();
a.C&&(g.Ln(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Oh(a.w,!1),g.Oh(a.A,!0))},Jra=function(a,b){a.B||(a.B=g.Bf(function(){A3(this);
Hra(this)},b,a))},A3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},B3=function(a){g.NP.call(this,a);
this.J=!1;this.H=0;this.F={};this.U=new kra(a);this.B=new g.P(this);g.H(this,this.B);this.C=this.w=null;this.B.L(this.player,"onVideoAreaChange",(0,g.x)(this.R,this,"onVideoAreaChange"));this.B.L(this.player,"onHideControls",(0,g.x)(this.R,this,"onHideControls"));this.B.L(this.player,"onShowControls",(0,g.x)(this.R,this,"onShowControls"));this.B.L(this.player,"resize",(0,g.x)(this.R,this,"resize"));this.B.L(this.player,"presentingplayerstatechange",(0,g.x)(this.R,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.kM,this);this.subscribe("resize",this.No,this);this.player.N().F.subscribe("vast_info_card_add",this.SA,this);this.S=new g.P(this);g.H(this,this.S);this.O=g.Ud("DIV","video-custom-annotations");this.u=new g.V({D:"div",X:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.ML(this.player,this.u.element,4);this.u.hide();this.A=new g.V({D:"div",X:["ytp-iv-video-content"]});g.H(this,this.A);g.Xd(this.A.element,g.Ud("DIV","video-annotations",
this.O));this.G=this.o=null;this.P=[];Kra(this)&&this.load();var b=g.Vd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.le(this,function(){g.$d(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Lra=function(){var a=g.Ud("DIV",["annotation",
"annotation-type-custom"]);g.Oh(a,!1);return a},Mra=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},Kra=function(a){var b=a.player.N();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.FC||b.F.get(a.videoId)||g.R(b.experiments,"allow_skip_annotations_invideo")&&(g.NB(a)||g.OB(a))?!0:!1},Nra=function(a,b,c){a.J=!0;
a.C=g.wp(b,c)},Ora=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Ora(a,e))}return c},Pra=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},Sra=function(a){var b=a.player.getVideoData();
if(b.Xd){var c=a.player.N().F.get(b.videoId);if(c){var d={format:"XML",Wd:{},method:"POST",withCredentials:!0};d.wd=(0,g.x)(function(e,f,k){Pra(this,e,f)||(e=g.qp(k)&&k.responseXML?k.responseXML:null)&&C3(this,e)},a,a.H,b.videoId);
g.Lp()&&(d.wd=Qra(a,d.wd));d.zb={ic_only:"1"};Rra(d,c);a.J=!0;g.wp(b.Xd,d)}}},Rra=function(a,b){a.method="POST";
a.zb=a.zb||{};b.Sm&&(a.zb.ic_coll=b.Sm);b.Tm&&(a.zb.ic_xml=b.Tm);b.hm&&(a.zb.ic_track=b.hm)},Tra=function(a){var b=new g.V({D:"div"});
g.Oh(b.element,!1);var c=new r3(a.player,b.element,D3(a));g.H(c,b);b.ba(a.u.element);c.Sl();return c},D3=function(a){if(!a.G){var b=new S2(a);
g.H(a,b);var c=new g.T1(a);g.H(a,c);a.G=new mra(b,c,a.player.N(),a.player.getVideoData(),a.U,a.player,a.kc)}return a.G},C3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Sr();if(e){var f=g.Qr();f&&g.gs(e,f,[g.Hr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=Ora(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=d3(k.type,Ura),t=d3(k.style,Vra),u=c3(k.data),z=0!=u.length?JSON.parse(u):{},C=Zqa(k.action);f=n&&p?new fra(n,p,t,C,z):null}else f=null}catch(ka){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=
!1}if(k){k=a;m=f;var D=Lra(),E=null;switch(m.type){case "branding":if(k.player.N().Oa)break;k.u.element.appendChild(D);E=new y3(D,D3(k),m);break;case "promotion":g.ML(k.player,D,4),E=new z3(D,D3(k),m)}E&&E.Sl();if(k=E)g.H(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=Tra(a),g.H(a,a.o));if("card"==f.type){if(c=a.o,E=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Rx:k.impression,click:k.click,close:k.close,eC:k.teaser_impression,tp:k.teaser_click},m=f.data.tracking_params||
{},D=null,E){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Hr(m.card):null,Td:m.teaser?g.Hr(m.teaser):null,pd:m.icon?g.Hr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,gB:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Hr(m.card):null,Td:m.teaser?g.Hr(m.teaser):null,pd:m.icon?g.Hr(m.icon):
null,Ci:f.data.image_url,Vv:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,ZF:!!f.data.is_paygated,mP:!!f.data.user_has_entitlement,url:e3({target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||
!1,Gc:k,Yd:m.card?g.Hr(m.card):null,Td:m.teaser?g.Hr(m.teaser):null,pd:m.icon?g.Hr(m.icon):null,Ci:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Hr(m.card):null,Td:m.teaser?g.Hr(m.teaser):null,pd:m.icon?g.Hr(m.icon):null,title:f.data.title,choices:f.data.choices,De:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,xi:f.data.signin_url?e3({target:"current",value:f.data.signin_url}):null,xP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};u3(c,f);break;case "productListing":f.data.signin_url&&(D=e3({target:"current",
value:f.data.signin_url}));E=[];for(var G=f.data.offers||[],F=0;F<G.length;F++)E.push(new jra(g.fd(G[F].merchant),g.fd(G[F].price)));f={AT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Hr(m.card):null,Td:m.teaser?g.Hr(m.teaser):null,pd:m.icon?g.Hr(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Mm:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),xi:D,PT:f.data.signin_title?f.data.signin_title:null,OT:f.data.signin_message?f.data.signin_message:null,offers:E};u3(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Hr(m.card):null,Td:m.teaser?g.Hr(m.teaser):null,pd:m.icon?g.Hr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Mm:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Gc:k,Yd:m.card?g.Hr(m.card):null,Td:m.teaser?g.Hr(m.teaser):
null,pd:m.icon?g.Hr(m.icon):null,Ci:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},u3(c,f)}}else wra(a.o,f);c=!0}}}c&&(J2(a.player),a.No())},Wra=function(a,b){var c=!1;
a.o||(a.o=Tra(a),g.H(a,a.o));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())xra(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.gA(b.headerText):"",g.de(c.ya,d),c.S&&c.S.setAttribute("title",d),c.ca=b.trackingParams?g.Hr(b.trackingParams):null,c.O=b.closeButton.infoCardIconRenderer.trackingParams?g.Hr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.Hr(b.icon.infoCardIconRenderer.trackingParams):null,J2(a.player),a.No())},
Xra=function(a,b,c,d,e){if(!a.player.N().Oa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new cra("openUrl","click",new ara("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.gA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.gA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.gA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.gA(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.gA(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.gA(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new fra(c,"branding","branding",f,d);d=Lra();a.u.element.appendChild(d);f=new y3(d,D3(a),f);f.Sl();g.H(f,f);a.F[c]=f}},Qra=function(a,b){return(0,g.x)(function(){if(!this.la()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ra.apply(window,c);this.P.push(g.Jp(b))}},a)},M2={},N2=null;g.Ta(P2,g.Mn);g.h=P2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(1==this.o)return!1;O2(this);this.startTime=a=(0,g.I)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.F=this.startTime;this.progress||this.B();this.re("play");-1==this.o&&this.re("resume");this.o=1;var b=g.Qa(this);b in M2||(M2[b]=this);Kqa();Lqa(this,a);return!0};
g.h.stop=function(a){O2(this);this.o=0;a&&(this.progress=1);Mqa(this,this.progress);this.re("stop");this.A()};
g.h.pause=function(){1==this.o&&(O2(this),this.o=-1,this.re("pause"))};
g.h.Y=function(){0==this.o||this.stop(!1);this.re("destroy");P2.Gb.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.nt=function(){this.re("animate")};
g.h.re=function(a){this.dispatchEvent(new Nqa(a,this))};
g.Ta(Nqa,g.oe);g.Ta(Q2,P2);Q2.prototype.C=g.Ia;Q2.prototype.nt=function(){this.C();Q2.Gb.nt.call(this)};
Q2.prototype.A=function(){this.C();Q2.Gb.A.call(this)};
Q2.prototype.B=function(){this.C();Q2.Gb.B.call(this)};
g.Ta(R2,Q2);R2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(S2,g.B);S2.prototype.ia=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Fq(a,b,c);this.o.push(a);return a};
S2.prototype.Sr=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Pq(a,b,c);this.o.push(a);return a};
S2.prototype.Wa=function(a){g.Gq(a);g.fb(this.o,a)};
S2.prototype.Y=function(){g.Gq(this.o);this.o.length=0;g.B.prototype.Y.call(this)};g.r(V2,g.NP);g.h=V2.prototype;g.h.load=function(){g.NP.prototype.load.call(this);if(!W2(this)){var a=g.MB(this.player.getVideoData());if(a)a=U2(a,Qqa(this)),X2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",wd:(0,g.x)(this.WK,this,a),Wd:{v:a},withCredentials:!0};this.J&&(a.Wd.ptype="embedded");var c=this.player.getVideoData().en;c&&(a.zb={ad_tracking:c});if(b=g.LB(b))if(b=g.Ec(b),b=g.Cc(b))this.A=g.wp(b,a)}}};
g.h.unload=function(){X2(this,null);this.A&&(this.A.abort(),this.A=null);g.NP.prototype.unload.call(this)};
g.h.Mc=function(a,b){if(!W2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=U2(b,"new");X2(this,c);return!0}return null};
g.h.getOptions=function(){return W2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.WK=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=U2(c,Qqa(this)))}X2(this,c)};
g.h.My=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Yra.length;f++){var k=Math.abs(b.width-Yra[f]);if(-1==e||d>=k)e=f,d=k}d=Zra[e];this.w&&g.th(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Mh(e.element,Math.round(k.width*a.width),f);g.Bh(e.element,m,n);g.Ln(e.element,$ra);m=k.left+k.width/2;k=k.top+l/2;g.K(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Ln(e.element,Zra);g.K(e.element,d);(e=g.Hd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.th(e,"height",f+"px")}}}}};
g.h.FG=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())a3(this,this.u.impressionUrls),(a=g.Sr())&&this.u.visualElement&&g.hs(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");g.K(g.sL(this.player),"ytp-ce-shown");a3(this,c.impressionUrls);(b=g.Sr())&&g.hs(b,c.visualElement);this.player.N().Eb&&this.player.ka("endscreenelementshown",a)}};
g.h.GG=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.Kn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);g.Kn(g.sL(this.player),"ytp-ce-shown");this.player.N().Eb&&this.player.ka("endscreenelementhidden",a)}};
g.h.MN=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c in b.o)g.Ln(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.rA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.In(c,"ytp-ce-element");){g.In(c,"subscribe-label")&&b3(this,a);if(g.In(c,"ytp-ce-channel-subscribe"))return;c=g.be(c)}if(!c||g.In(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.xt(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.QO?(b3(this,a),this.JB(),this.player.pauseVideo(),c=g.Ec(Z2(this,a.targetUrl)),c=g.Cc(c),g.PM(c,void 0,a.Nb)):(c=this.player.getVideoData().uc,
c=(0,g.x)(this.KO,this,c,Z2(this,a.targetUrl),a.Nb),c=(0,g.x)(this.JB,this,c),b3(this,a,c))}}};
g.h.KO=function(a,b,c){var d=g.ep(b);a&&d&&(d.v||d.list)?g.NT(this.player.app,d.v,c,d.list,!1,void 0):g.OM(b,c)};
g.h.qs=function(a,b){g.In(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.K(a.element,"ytp-ce-element-hover"):this.player.N().o?(new g.J(function(){g.K(a.element,"ytp-ce-element-hover")},200)).start():g.K(a.element,"ytp-ce-element-hover"),a3(this,b.MF),$2(this,b.id,!0))};
g.h.xt=function(a,b){g.Kn(a.element,"ytp-ce-element-hover");g.Kn(a.element,"ytp-ce-force-expand");$2(this,b.id,!1)};
g.h.JB=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Yra=[346,426,470,506,570,640,853,1280,1920],Zra="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),$ra=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var bra={CQ:"current",XR:"new"};var dra={CLOSE:"close",aS:"openUrl",BD:"subscribe"},era={wQ:"click",CLOSE:"close",nR:"hidden",FS:"rollOut",GS:"rollOver",JS:"shown"};var Vra={ZP:"anchored",VC:"branding",CHANNEL:"channel",BQ:"cta",pR:"highlightText",GR:"label",PLAYLIST:"playlist",sS:"popup",NS:"speech",BD:"subscribe",YS:"title",VIDEO:"video",lT:"website"},Ura={VC:"branding",nQ:"card",IQ:"drawer",oR:"highlight",NR:"marker",xS:"promotion",TEXT:"text",nT:"widget"};h3.prototype.u=function(a,b){var c=g.ie(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
h3.prototype.A=function(a,b){var c=g.ie(b.target,null,"iv-card-poll",void 0);if(c)if(a.xi)g.Jd("iv-card-sign-in-button",c).click();else{var d=parseInt(Gqa(b.target),10);if(null==a.De)a.choices[d].count++,a.De=d;else if(a.De!=d){var e=a.choices[a.De];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.De=d}else e=a.choices[a.De],e.count=Math.max(e.count-1,0),a.De=null;ora(a,c);g.Ap(this.o.videoData.Xd,{Wd:{action_poll_vote:1},zb:{poll_id:a.id,index:d,session_token:a.xP}});g3(this.o.logger,a.Gc.click,
void 0,5);(c=g.Sr())&&a.Yd&&g.is(c,a.Yd)}};g.r(n3,g.B);g.h=n3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.SD(a,b,{id:c});g.H(this,a);a.namespace="annotations_module";d&&Fqa(a).subscribe("onEnter",d,this);e&&Fqa(a).subscribe("onExit",e,this);g.IL(this.context.aa,[a])};
g.h.Sl=function(){this.context.u.subscribe("resize",this.Om,this)};
g.h.Jj=function(a,b,c,d,e,f){this.context.o.ia(a,"click",g.Ra(this.Tn,b,c,d,e||[],f||0),this);this.context.o.ia(a,"touchstart",g.Ra(function(){this.Gu=!1}),this);
this.context.o.ia(a,"touchmove",g.Ra(function(){this.Gu=!0}),this)};
g.h.Tn=function(a,b,c,d,e,f){if(this.Gu)return!1;f&&(f.stopPropagation(),f.preventDefault());ura(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.$d(this.o)};
g.h.Om=function(){};g.r(r3,n3);g.h=r3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=g.sL(this.w))?(a=g.Nh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Om=function(){var a=this.isAvailable();g.Oh(this.o,a);g.L(g.sL(this.context.aa),"ytp-iv-drawer-enabled",a);J2(this.w)};
g.h.destroy=function(){var a=g.AL(g.nL(this.w));a&&a.ls(!1,void 0);try{g.sL(this.w).removeChild(this.F)}catch(b){}g.Po(this.V);g.Gq(this.ea);this.ga&&this.ga.dispose();this.G&&this.G.dispose();n3.prototype.destroy.call(this)};
g.h.ZG=function(a){this.Z.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.KB=function(a){if(!g.In(g.sL(this.w),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.Sr(),c=this.u?this.u.card.pd:this.J;b&&c&&L2(b,[c]);this.u=a;v3(this)}if(b="none"!=this.o.style.display)2==this.context.aa.getPresentingPlayerType()?b=1==this.context.aa.getAdState():(b=this.context.aa.getPlayerState(),c=0==b&&0===this.context.aa.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.AL(g.nL(this.w)))&&c.ls(!0,b));
this.sa.isActive()||((!this.C||!this.Z.isActive()&&this.da)&&Era(this,a),this.sa.start(910+a.card.teaserDurationMs))}};
g.h.CO=function(a){this.C||(this.u=a,v3(this),Era(this,a),p3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.eE=function(){if(this.C){g3(this.context.logger,w3(this).Gc.close);var a=g.Sr();a&&this.O&&g.is(a,this.O);q3(this)}};
g.h.rE=function(){g.L(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.hG=function(){var a=g.Sr(),b=w3(this);b=b?b.pd:this.J;a&&b&&K2(a,[b])};
g.h.gG=function(){var a=g.Sr(),b=w3(this);b=b?b.pd:this.J;a&&b&&L2(a,[b])};
g.h.kG=function(){var a=w3(this);g3(this.context.logger,a.Gc.eC);var b=g.Sr();b&&a&&K2(b,[a.Td,a.pd])};
g.h.jG=function(){var a=g.Sr(),b=w3(this);a&&b&&L2(a,[b.Td])};
g.h.iG=function(a){var b=w3(this),c=g.Sr();this.u?a?(a=this.context.logger,g3(a,b.Gc.tp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Td&&g.is(c,b.Td)):(a=this.context.logger,g3(a,b.Gc.tp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.pd&&g.is(c,b.pd)):(a=this.context.logger,g3(a,b.Gc.tp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.is(c,this.J))};g.r(x3,n3);x3.prototype.Sl=function(){n3.prototype.Sl.call(this);Fra(this)};
x3.prototype.show=function(){n3.prototype.show.call(this);var a=g.Sr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&K2(a,[g.Hr(b.itct)])};
x3.prototype.hide=function(){n3.prototype.hide.call(this);var a=g.Sr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&L2(a,[g.Hr(b.itct)])};g.r(y3,x3);g.h=y3.prototype;g.h.LO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Nh(a);this.u||(g.Lh(a,e.width),g.Lh(b,e.width));g.th(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.th(c,"right","1px");this.B=!0;g.Oh(a,!0);this.C=new g.J(function(){g.K(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.LF=function(a,b){g.Kn(this.o,"iv-branding-active");this.F=new g.J((0,g.x)(function(){g.Oh(a,!1);this.u||g.Lh(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){x3.prototype.show.call(this);if(!this.G){g.K(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Ud("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Oh(this.w,!1);var b=g.Ud("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=hra(this.annotation))&&this.Jj(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Ud("DIV","iv-branding-context-name");
g.de(c,a.channel_name);var d=g.Ud("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.tQ(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.aa),this.u.ba(d);b=g.Ud("DIV","iv-branding-context-subscribe-caret");c=g.Ud("DIV","branding-context-container-inner",b,c,d);g.Oh(c,!1);d=g.Ud("DIV","branding-context-container-outer",c);g.th(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.J(g.Ra(this.LF,c,d),500,this);g.H(this,this.A);this.context.o.ia(this.o,"mouseover",(0,g.x)(this.LO,this,c,d,b,a.image_height));this.context.o.ia(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Oh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.Gh(a);c=g.Nh(a);b=(new g.qh(b.x,b.y,c.width,c.height)).width;g.Bh(a,b);e=new R2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,Hqa);g.H(this,e);this.context.w.ia(e,
"begin",g.Ra(g.Oh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(x3.prototype.hide.call(this),g.Oh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);x3.prototype.destroy.call(this)};g.r(z3,x3);g.h=z3.prototype;g.h.show=function(){this.isActive||(x3.prototype.show.call(this),this.P||(Gra(this),this.P=!0),g.Oh(this.o,!0),g.Bf(function(){g.Kn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,A3(this),Ira(this),Jra(this,this.G))};
g.h.hide=function(){this.isActive&&(g.K(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.Tn=function(a,b,c,d,e,f){return this.C?!1:x3.prototype.Tn.call(this,a,b,c,d,e,f)};
g.h.mr=function(a,b){b.stopPropagation();Ira(this);Jra(this,a);this.u.focus()};
g.h.pF=function(a){this.J=!0;this.mr(500,a)};
g.h.oF=function(){this.J=!1;Hra(this)};
g.h.gF=function(a){a.stopPropagation();this.hide()};
g.h.hF=function(a){a.stopPropagation();A3(this);this.C=!0;g.K(this.o,"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();x3.prototype.destroy.call(this)};g.r(B3,g.NP);g.h=B3.prototype;g.h.Mc=function(a,b){if(!Mra(this.player.N().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.S1(b);c&&C3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(zra(this.o,b),J2(this.player)),!0}return null};
g.h.getOptions=function(){return Mra(this.player.N().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.No=function(){if(this.A){var a=g.rL(this.player).getVideoContentRect(!0);g.Mh(this.A.element,a.width,a.height);g.Bh(this.A.element,a.left,a.top)}if(this.o){var b=g.DL(this.player);a=this.o;b=b.width;g.L(a.F,"iv-drawer-small",426>=b);g.L(a.F,"iv-drawer-big",1280<=b)}};
g.h.kM=function(a){this.oc(a.state);g.W(a.state,2)&&(this.kl()&&this.Ky()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.ls(!1))};
g.h.load=function(){g.NP.prototype.load.call(this);this.oc(g.uL(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.YK,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.Lp()&&(c=Qra(this,c));c={format:"XML",wd:c,onError:d,Wd:{}};a.isPharma&&(c.Wd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.N().F.get(b))&&Rra(c,b);b=b&&(b.Tm||b.Sm);if(!a.Gm||b)a.Xd?Nra(this,a.Xd,c):(this.w=(0,g.x)(this.DG,this,c),this.player.addEventListener("videodatachange",this.w));g.ML(this.player,this.A.element,4);this.No();(b=g.NB(a))&&Wra(this,b);(b=g.OB(a))&&b.featuredChannel&&Xra(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.oc=function(a){a=!a.isCued()&&!g.W(a,1024);g.FC(this.u,a);g.FC(this.A,a)};
g.h.DG=function(a){var b=this.player.getVideoData();b.Xd&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),Nra(this,b.Xd,a))};
g.h.unload=function(){g.dR(this.player.app,"annotations_module",void 0);g.Ob(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,J2(this.player));this.J=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.NP.prototype.unload.call(this);g.CC(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.YK=function(a,b,c){this.C=null;!Pra(this,b,a)&&(a=g.qp(c)&&c.responseXML?c.responseXML:null)&&(C3(this,a),g.K(g.sL(this.player),"iv-module-loaded"))};
g.h.SA=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Sra(this):this.load())};
g.h.kl=function(){return!!this.o&&this.o.isAvailable()};
g.h.Ky=function(){this.kl();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.kl();this.o&&(a?c?p3(this.o,c,b):p3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):q3(this.o))};
g.h.ls=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.N().F.unsubscribe("vast_info_card_add",this.SA,this);g.Kn(g.sL(this.player),"ytp-iv-drawer-open");for(var a=this.P,b=0,c=a.length;b<c;b++)g.Mp(a[b]);this.P.length=0;g.NP.prototype.Y.call(this)};g.bQ.annotations_module=B3;g.bQ.creatorendscreen=V2;})(_yt_player);
