(function(g){var window=this;var W4=function(a,b,c){var d=b.wa();g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Bc(c?c:"mqdefault.jpg");var f=b instanceof g.cB&&b.lengthSeconds?g.bM(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.WD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.cB?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.dk||g.LM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Rh(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.YD&&(d.playlist_length=b.getLength());a.update(d)},X4=function(a){g.V.call(this,{D:"div",
X:["ytp-upnext","ytp-player-content"],M:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",M:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",W:"Up Next"},{D:"span",I:"ytp-upnext-title",W:"{{title}}"},{D:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",M:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",M:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
I:"ytp-svg-autoplay-circle",M:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",M:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",M:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",W:"Autoplay is paused"}]}]});
this.B=null;var b=this.o["ytp-upnext-cancel"];this.B=new g.V({D:"button",X:["ytp-upnext-cancel-button","ytp-button"],M:{tabindex:"0","aria-label":"Cancel autoplay"},W:"Cancel"});g.H(this,this.B);this.B.ia("click",this.vK,this);this.B.ba(b);this.u=a;this.J=this.o["ytp-svg-autoplay-ring"];this.F=this.C=this.w=this.A=null;this.G=new g.J(this.Ym,5E3,this);g.H(this,this.G);this.H=0;this.L(this.o["ytp-upnext-autoplay-icon"],"click",this.fM);this.jA();this.L(a,"autonavvisibility",this.jA);this.L(a,"mdxnowautoplaying",
this.xL);this.L(a,"mdxautoplaycanceled",this.yL);this.L(a,"mdxautoplayupnext",this.zC);3==this.u.getPresentingPlayerType()&&(a=(a=g.vL(g.nL(this.u)))?a.WE():null)&&this.zC(a);g.L(this.element,"ytp-upnext-mobile",this.u.N().o)},Y4=function(a,b){if(!a.w){g.Qo("a11y-announce","Up Next "+a.A.title);
a.H=(0,g.O)();a.w=new g.J((0,g.x)(a.bq,a,b),25);a.bq(b);var c=b||g.S(a.u.N().experiments,"autoplay_time")||1E4;a.u.ka("onAutonavCoundownStarted",c)}g.Kn(a.element,"ytp-upnext-autoplay-paused")},$4=function(a){Z4(a);
a.H=(0,g.O)();a.bq();g.K(a.element,"ytp-upnext-autoplay-paused")},Z4=function(a){a.w&&(a.w.dispose(),a.w=null)},a5=function(a,b){b=void 0===b?!1:b;
if(g.R(a.u.N().experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.A.wa(),a.Ym(),a.C=new Notification("Up Next",{body:c.title,icon:c.Bc()}),a.F=a.L(a.C,"click",a.WL),a.G.start())}Z4(a);a.u.nextVideo(!1,b)},b5=function(a,b){g.V.call(this,{D:"div",
X:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},lta=function(a){b5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.V({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",M:{src:b.Qd}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",W:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.H(this,this.u);this.u.ba(this.element);this.subscribeButton=new g.tQ("Subscribe",null,"Unsubscribe",null,!0,!1,b.wg,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.subscribeButton);this.subscribeButton.ba(this.u.o["html5-subscribe-button-container"]);
this.hide()},c5=function(a){var b=a.N(),c=g.Gv||g.wh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",X:e,M:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",M:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",M:c,K:[{D:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",W:"Live"},{D:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",X:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",X:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.suggestion=null;this.w=d;this.api=a;this.u=new g.P(this);g.H(this,this.u);this.ia("click",this.onClick);this.ia("keypress",this.B);this.u.L(a,"videodatachange",this.A);g.PL(a,this.element,this);this.A()},mta=function(a){var b=a.suggestion.wa().videoId,c=a.suggestion.getPlaylistId();
(g.NT(a.api.app,b,a.suggestion.Nb,c,void 0,void 0)||a.api.fa("web_player_endscreen_double_log_fix_killswitch"))&&g.RL(a.api,a.element)},d5=function(a){b5.call(this,a,"videowall-endscreen");
var b=this;this.aa=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.H=!1;this.G=null;this.w=new g.P(this);g.H(this,this.w);this.F=new g.J(function(){g.K(b.element,"ytp-show-tiles")},0);
g.H(this,this.F);var c=new g.V({D:"button",X:["ytp-button","ytp-endscreen-previous"],M:{"aria-label":"Previous"},K:[g.jM()]});g.H(this,c);c.ba(this.element);c.ia("click",this.iH,this);this.table=new g.BC({D:"div",I:"ytp-endscreen-content"});g.H(this,this.table);this.table.ba(this.element);c=new g.V({D:"button",X:["ytp-button","ytp-endscreen-next"],M:{"aria-label":"Next"},K:[g.kM()]});g.H(this,c);c.ba(this.element);c.ia("click",this.hH,this);this.u=new X4(a);g.H(this,this.u);g.ML(this.player,this.u.element,
4);this.hide()},e5=function(a){return g.NL(a.player)&&a.Tv()&&!a.B},nta=function(a,b){return(0,g.A)(b.suggestions,function(c){c=g.pO(a.aa.N(),c);
g.H(a,c);return c})},f5=function(a){var b=a.ws();
b!==a.H&&(a.H=b,a.player.R("autonavvisibility"))},g5=function(a){g.NP.call(this,a);
this.endScreen=null;this.listeners=new g.P(this);g.H(this,this.listeners);this.o=a.N();ota(a)?this.endScreen=new d5(this.player):this.o.Ia?this.endScreen=new lta(this.player):this.endScreen=new b5(this.player);g.H(this,this.endScreen);g.ML(this.player,this.endScreen.element,4);this.DB();this.listeners.L(a,"videodatachange",this.DB,this);this.listeners.L(a,g.VD("endscreen"),this.fH,this);this.listeners.L(a,"crx_endscreen",this.NK,this)},ota=function(a){a=a.N();
return a.Ha&&!a.Ia};
g.r(X4,g.V);g.h=X4.prototype;g.h.Ym=function(){this.C&&(this.G.stop(),this.Wa(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.jA=function(){g.FC(this,g.oL(this.u))};
g.h.WL=function(){window.focus();this.Ym()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.bq=function(a){a=a||g.S(this.u.N().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.O)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?a5(this,!0):this.w&&this.w.start()};
g.h.fM=function(a){!g.ce(this.B.element,g.Hq(a))&&g.RM(a,this.u)&&a5(this)};
g.h.vK=function(){g.qL(this.u,!0)};
g.h.xL=function(a){this.u.getPresentingPlayerType();this.show();Y4(this,a)};
g.h.zC=function(a){this.u.getPresentingPlayerType();this.A&&this.A.wa().videoId==a.wa().videoId||(this.A=a,W4(this,a,"hqdefault.jpg"))};
g.h.yL=function(){this.u.getPresentingPlayerType();Z4(this);this.hide()};
g.h.Y=function(){Z4(this);this.Ym();g.V.prototype.Y.call(this)};g.r(b5,g.V);g.h=b5.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.Tv=function(){return!1};
g.h.ws=function(){return!1};
g.h.hy=function(){return!1};g.r(lta,b5);g.r(c5,g.V);c5.prototype.onClick=function(a){g.RM(a,this.api,this.w,this.suggestion.Nb||void 0)&&mta(this)};
c5.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.Mq(a)||(mta(this),g.Lq(a))}};
c5.prototype.A=function(){var a=this.api.getVideoData(),b=this.api.N();this.w=a.uc?!1:b.u};g.r(d5,b5);g.h=d5.prototype;g.h.create=function(){b5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=nta(this,a),this.videoData=a);this.sg();this.w.L(this.player,"appresize",this.sg);this.w.L(this.player,"onVideoAreaChange",this.sg);this.w.L(this.player,"videodatachange",this.jH);this.w.L(this.player,"autonavchange",this.xs);this.w.L(this.player,"autonavcancel",this.gH);a=this.videoData.autonavState;a!==this.G&&this.xs(a);this.w.L(this.element,"transitionend",this.wN)};
g.h.destroy=function(){g.vr(this.w);g.ne(this.stills);this.stills=[];this.suggestions=null;b5.prototype.destroy.call(this);g.Kn(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.h.Tv=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){b5.prototype.show.call(this);g.Kn(this.element,"ytp-show-tiles");this.player.N().o?g.An(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.qL(this.player,!1);e5(this)?(f5(this),2===this.videoData.autonavState?g.R(this.player.N().experiments,"fast_autonav_in_background")&&3===this.player.getVisibilityState()?a5(this.u,!0):Y4(this.u):3===this.videoData.autonavState&&$4(this.u)):(g.qL(this.player,!0),f5(this))};
g.h.hide=function(){b5.prototype.hide.call(this);$4(this.u);f5(this)};
g.h.wN=function(a){g.Hq(a)===this.element&&this.sg()};
g.h.sg=function(){if(this.suggestions&&this.suggestions.length){g.K(this.element,"ytp-endscreen-paginate");var a=g.DL(this.aa,!0,this.aa.isFullscreen()),b=g.WC(this.aa);b&&(b=b.jc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,t=e/2,u=b<=f-2&&n>=t*m,z=e<=k-2&&n>=p*m;if((p+1)/t*d/c>c/(p/(t+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=
t*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.sd(a.width/m||1,1,1.21);n*=g.sd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.Mh(a,m,n);g.th(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.A=f;W4(c,f,"hqdefault.jpg");g.L(this.element,"ytp-endscreen-takeover",e5(this));f5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),p=g.td(p+this.A,l),0!==t){u=this.stills[c];u||(u=new c5(this.player),this.stills[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),D=Math.floor(n*(k+t)/e)-z-4,E=Math.floor(m*(f+t)/b)-C-4;g.Bh(u.element,C,z);g.Mh(u.element,E,D);g.th(u.element,"transitionDelay",(k+f)/20+"s");g.L(u.element,"ytp-videowall-still-mini",1===t);g.L(u.element,"ytp-videowall-still-large",
2<t);t=u;p=this.suggestions[p];t.suggestion!==p&&(t.suggestion=p,u=t.api.N(),z=g.In(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",W4(t,p,z),g.ux(u)&&(u=p.Rh(),u=g.eh(u,g.FD({},"emb_rel_end")),t.ha("url",u)),(p=(p=p.Nb)&&p.itct)&&g.QL(t.api,t.element,p));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.$d(e.element),g.me(e);this.stills.length=c}};
g.h.jH=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=nta(this,a),this.videoData=a,this.sg())};
g.h.hH=function(){this.A+=this.stills.length;this.sg()};
g.h.iH=function(){this.A-=this.stills.length;this.sg()};
g.h.hy=function(){return!!this.u.w};
g.h.xs=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,Z4(this.u),this.Fa()&&this.sg()):(this.C=!0,this.Fa()&&e5(this)&&(2===a?Y4(this.u):3===a&&$4(this.u)))};
g.h.gH=function(a){if(a){for(a=0;a<this.stills.length;a++)g.SL(this.aa,this.stills[a].element,!0);this.xs(1)}else this.B=null,this.C=!1;this.sg()};
g.h.ws=function(){return this.Fa()&&e5(this)};g.r(g5,g.NP);g.h=g5.prototype;g.h.Uy=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!ota(this.player)||b;var c=a.Hi||g.Dx(a.La),d=g.hT(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Ty=function(){return this.endScreen.ws()};
g.h.UF=function(){return this.Ty()?this.endScreen.hy():!1};
g.h.Y=function(){g.dR(this.player.app,"endscreen",void 0);g.NP.prototype.Y.call(this)};
g.h.load=function(){g.NP.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.NP.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.fH=function(a){this.Uy()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.NK=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.DB=function(){g.dR(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.SD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.H(this,a);var b=new g.SD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.H(this,b);g.IL(this.player,[a,b])};g.bQ.endscreen=g5;})(_yt_player);
